"""Server projects, assigned schedules and desktop command queue."""
from alembic import op
import sqlalchemy as sa

revision = "20260926_control"
down_revision = "20260925_admin_entitlement"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('brand_name', sa.String(length=120), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('queries_json', sa.Text(), nullable=False),
    sa.Column('schedule_json', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_projects_user_id'), 'control_projects', ['user_id'], unique=False)
    op.create_table('device_connect',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('local_project_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['control_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', 'local_project_id')
    )
    op.create_index(op.f('ix_control_links_user_id'), 'control_links', ['user_id'], unique=False)
    op.create_table('control_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('desired_state', sa.String(length=24), nullable=False),
    sa.Column('active_project_key', sa.String(length=100), nullable=True),
    sa.Column('active_device_key', sa.String(length=100), nullable=True),
    sa.Column('request_key', sa.String(length=160), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('progress_json', sa.Text(), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['control_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_device_key'),
    sa.UniqueConstraint('active_project_key'),
    sa.UniqueConstraint('request_key')
    )
    op.create_index(op.f('ix_control_runs_project_id'), 'control_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_control_runs_user_id'), 'control_runs', ['user_id'], unique=False)
    op.create_table('device_grants',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['token_hash'], ['sessions.token_hash'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_device_grants_user_id'), 'device_grants', ['user_id'], unique=False)
    op.add_column('agent_devices', sa.Column('revoked', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('agent_devices', sa.Column('capabilities_json', sa.Text(), nullable=False, server_default='{}'))
    op.add_column('cloud_results', sa.Column('project_id', sa.String(length=32), nullable=True))
    op.add_column('cloud_results', sa.Column('query_id', sa.String(length=32), nullable=True))
    op.add_column('cloud_results', sa.Column('run_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_cloud_results_project_id'), 'cloud_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_cloud_results_run_id'), 'cloud_results', ['run_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloud_results_run_id'), table_name='cloud_results')
    op.drop_index(op.f('ix_cloud_results_project_id'), table_name='cloud_results')
    op.drop_column('cloud_results', 'run_id')
    op.drop_column('cloud_results', 'query_id')
    op.drop_column('cloud_results', 'project_id')
    op.drop_column('agent_devices', 'capabilities_json')
    op.drop_column('agent_devices', 'revoked')
    op.drop_index(op.f('ix_device_grants_user_id'), table_name='device_grants')
    op.drop_table('device_grants')
    op.drop_index(op.f('ix_control_runs_user_id'), table_name='control_runs')
    op.drop_index(op.f('ix_control_runs_project_id'), table_name='control_runs')
    op.drop_table('control_runs')
    op.drop_index(op.f('ix_control_links_user_id'), table_name='control_links')
    op.drop_table('control_links')
    op.drop_table('device_connect')
    op.drop_index(op.f('ix_control_projects_user_id'), table_name='control_projects')
    op.drop_table('control_projects')
    # ### end Alembic commands ###
